### ISSUE TITLE
[Feature request] Allow custom script host

### ISSUE THREAD

**Issue by matthiasferch** [yociduo/ngx-pendo#1]
Hi! We're using Pendo from within the EU, which requires us to use a different script host (https://cdn.eu.pendo.io). I would like to propose adding a optional script host url to the plugin's settings:

```
export interface IPendoSettings {
  pendoApiKey: string;
  pendoScriptHost?: string;
  pendoIdFormatter?: (pendoId: string) => string;
}
```

I have prepared a PR but I cannot upload it without write access to the repo, of course.

**Comment by yociduo** [comment]
Could you fork one?

**Comment by matthiasferch** [comment]
Here you go:
https://github.com/yociduo/ngx-pendo/pull/2

**Comment by yociduo** [comment]
Merged, I will bump a new version tomorrow.
