### ISSUE TITLE
Pendo is not initialized if service is injected in APP_INITIALIZER

### ISSUE THREAD

**Issue by llRandom** [yociduo/ngx-pendo#108]
I have a service injected in angular `APP_INITIALIZER`. This service has dependency on `NgxPendoService`. `NgxPendoService` is not initialized properly after upgrade to angular 18 because `window.pendo` is not set when `NgxPendoService` is created.

Application initialization is failing with an error
```
core.mjs:7188 ERROR TypeError: Cannot read properties of undefined (reading 'initialize')
    at _NgxPendoService.initialize (ngx-pendo.mjs:39:18)
    at _AppService.initPendo (app.service.ts:17:23)
    at _AppComponent.ngOnInit (app.component.ts:17:21)
    at callHookInternal (core.mjs:5007:10)
    at callHook (core.mjs:5031:7)
    at callHooks (core.mjs:4991:9)
    at executeInitAndCheckHooks (core.mjs:4946:5)
    at refreshView (core.mjs:13355:11)
    at detectChangesInView (core.mjs:13549:5)
    at detectChangesInViewWhileDirty (core.mjs:13260:5)
```

app.module.ts
```
import { APP_INITIALIZER, NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { NgxPendoModule } from 'ngx-pendo';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AppService } from './app.service';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgxPendoModule.forRoot({
      pendoApiKey: key
    })
  ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: (service: AppService) => () => service.initApp(),
      deps: [AppService],
      multi: true
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

app.service
```
import { Injectable } from '@angular/core';
import { NgxPendoService } from 'ngx-pendo';

@Injectable({
  providedIn: 'root'
})
export class AppService {
  constructor(
    private pendoService: NgxPendoService,
  ) { }

  initApp() {
    // some complex init
  }

  initPendo() {
    this.pendoService.initialize({ id: '1' }, { id: '1' });
  }
}
```

app.component.ts
```
import { Component, OnInit } from '@angular/core';
import { AppService } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements OnInit {
  title = 'test';

  constructor(
    private appService: AppService
  ) { }

  ngOnInit(): void {
    this.appService.initPendo();
  }
}
```

angular version: 18.1.0
ngx-pendo version: 2.0.0

**Comment by MaximBelov** [comment]
@llRandom 
Hi 
You cant use this.pendoService.initialize in APP_INITIALIZER
Reason:
See: https://github.com/yociduo/ngx-pendo/blob/main/projects/ngx-pendo/src/lib/ngx-pendo.injectors.ts#L42

Solutions: 
1 Wait for new release with fix
https://github.com/yociduo/ngx-pendo/pull/107
and implement your on initiazer

OR
2 Create AppNgxPendoModule and provide a custom function for APP_INITIALIZER provider

`
@NgModule({
  imports: [NgxPendoIdDirective, NgxPendoSectionDirective],
  exports: [NgxPendoIdDirective, NgxPendoSectionDirective]
})
export class AppNgxPendoModule {
  static forRoot(settings: IPendoSettings): ModuleWithProviders<AppNgxPendoModule> {
    return {
      ngModule: NgxPendoModule,
      providers: [
        {
          provide: NGX_PENDO_SETTINGS_TOKEN,
          useValue: settings
        },
        NGX_PENDO_INITIALIZER_PROVIDER
      ]
    };
  }

  static forChild(): ModuleWithProviders<NgxPendoModule> {
    return {
      ngModule: NgxPendoModule
    };
  }
}


export const NGX_PENDO_INITIALIZER_PROVIDER: Provider = {
  provide: APP_INITIALIZER,
  multi: true,
  useFactory: pendoInitializer,
  deps: [NGX_PENDO_SETTINGS_TOKEN, NGX_PENDO_WINDOW]
};

export function pendoInitializer($settings: IPendoSettings, window: PendoWindow): () => Promise<void> {
  return async () => {
   // Load pendo script
  };
}


`

**Comment by llRandom** [comment]
Thanks @MaximBelov, will wait for a new version. I don't call `this.pendoService.initialize` in `APP_INITIALIZER`. I only inject a service that depends on `NgxPendoService`. The workaround I found is to not inject `NgxPendoService` in this service and get it with `Injector` before calling `this.pendoService.initialize`

**Comment by MaximBelov** [comment]
@llRandom 
You call the constructor of NgxPendoService in AppService:
`AppModule -> APP_INITIALIZER -> constructor AppService -> constructor NgxPendoService `

But the constructor of NgxPendoService should call in NgxPendoModule
`AppModule -> NgxPendoModule -> NGX_PENDO_INITIALIZER_PROVIDER -> APP_INITIALIZER`

**Comment by yociduo** [comment]
@MaximBelov
Please using following code to implement your requirement. Manually wait for NGX_PENDO_CONTEXT to initialize, then get the AppService from Injector.

```
import { APP_INITIALIZER, Injector, NgModule } from '@angular/core';

...

@NgModule({
  declarations: [AppComponent],
  imports: [
    ...
    NgxPendoModule.forRoot({
      pendoApiKey: 'pendo-api-key',
      pendoIdFormatter: kebabCase
    })
  ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: (injector: Injector) => async () => {
        await new Promise<void>(resolve => {
          const sub = interval(100).subscribe(() => {
            if (injector.get(NGX_PENDO_CONTEXT)) {
              sub.unsubscribe();
              resolve();
            }
          });
        });
        injector.get(AppService).initApp();
      },
      deps: [Injector],
      multi: true
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by llRandom** [comment]
@yociduo just to confirm, there would be no fix for this, only workaround above?

**Comment by yociduo** [comment]
@llRandom Yes. It should be working in 2.0.0, and the new feature has been release in 2.1.0.
