### ISSUE TITLE
build throw error of ERROR in The target entry-point "ngx-pendo" has missing dependencies:

### ISSUE THREAD

**Issue by ofirrifo** [yociduo/ngx-pendo#13]
I upgrade from angular 9 to 10 and I get 
ERROR in The target entry-point "ngx-pendo" has missing dependencies:

```
ERROR in The target entry-point "ngx-pendo" has missing dependencies:
 - ./lib/ngx-pendo-id.directive
 - ./lib/ngx-pendo-section.directive
 - ./lib/ngx-pendo.service
 - ./lib/ngx-pendo.component
 - ./lib/ngx-pendo.injectors
 - ./lib/ngx-pendo.interfaces
 - ./lib/ngx-pendo.module

```

**Comment by yociduo** [comment]
Which version for the `ngx-pendo`?

**Comment by ofirrifo** [comment]
@yociduo I'm using  "ngx-pendo": "^1.4.0",

**Comment by thizanetti** [comment]
I get a similar (not sure if related problem) on angular 7.2.16, node 12.16.3 for build ngx-pendo@1.4.0 on both mac and linux:
```
ERROR in Couldn't resolve original symbol for ./lib/ngx-pendo-id.directive from ../node_modules/ngx-pendo/ngx-pendo.d.ts
```

Maybe that's a bad build?

**Comment by thizanetti** [comment]
Reverting back to 1.3.0 fixed that issue for me FYI.

**Comment by ofirrifo** [comment]
@thizanetti I also revert to 1.3.0 and it solve the issue.
Thanks :)

**Comment by yociduo** [comment]
@ofirrifo @thizanetti  Please upgrade to 1.4.1, it resolve this issue

**Comment by ofirrifo** [comment]
@yociduo Thanks it work great 👍
