### ISSUE TITLE
App is getting blocked

### ISSUE THREAD

**Issue by bhaskarmishra** [yociduo/ngx-pendo#3]
App loading gets blocked if there is some issue with the pendo url/connectivity. I see there is no error handling. In order to replicate, just block the pendo url using dev tools and the app just hangs. Ideally, it should allow app to load even if there is an issue with pendo.

**Comment by EricTendian** [comment]
I've found that Pendo is blocked by quite a few adblockers, I had to disable adblock on the page I was using it on for it to load.

**Comment by bhaskarmishra** [comment]
That's correct @EricTendian,  Any blocking of Pendo should not stop the app from loading.

**Comment by yociduo** [comment]
I will handle on this

**Comment by bhaskarmishra** [comment]
Thanks @yociduo, will wait for the release.

**Comment by yociduo** [comment]
@bhaskarmishra @EricTendian Bump a new version for v1.2.2. 
I still want to use RxJS to solve this problem. Pendo script still needs 5 ~ 10 seconds to load in China, which means there will be a long initialization time. This change is in progress and will be released in the next major release
https://github.com/yociduo/ngx-pendo/compare/rxjs

**Comment by bhaskarmishra** [comment]
Thanks @yociduo
