### ISSUE TITLE
Application breaks if the app cannot obtain the pendo JS file

### ISSUE THREAD

**Issue by doronsever** [yociduo/ngx-pendo#5]
If for some reason the application cannot obtain the js file (for instance something wrong in nginx or someone blocked it) the whole application breaks.
This shouldn't happen.
To fix this, all you need to do is not to reject the promise in 

> ngx-pendo.injector.js

I have a PR ready but don't have access to push it...

**Comment by yociduo** [comment]
You can fork one.

**Comment by doronsever** [comment]
@yociduo you have a PR waiting

**Comment by yociduo** [comment]
I still want to use RxJS to solve this problem. Pendo script still needs 5 ~ 10 seconds to load in China, which means there will be a long initialization time. This change is in progress and will be released in the next major release
https://github.com/yociduo/ngx-pendo/compare/rxjs
