### ISSUE TITLE
bump angular 15

### ISSUE THREAD

**Issue by damingerdai** [yociduo/ngx-pendo#59]

**Comment by aletatan** [comment]
are you gonna make the angular 15 upgrade?
thanks in advance!

**Comment by PooSham** [comment]
Seems like Circle CI failed, so there is no new release. Would be nice to get angular 15 support @damingerdai

**Comment by damingerdai** [comment]
> Seems like Circle CI failed, so there is no new release. Would be nice to get angular 15 support @damingerdai

@yociduo 

```
No .circleci/config.yml was found in your project. Add a configuration file to your repository or refer to [documentation](https://circleci.com/docs/2.0/configuration-reference/).
```

please remove Circle CI

**Comment by PooSham** [comment]
> > Seems like Circle CI failed, so there is no new release. Would be nice to get angular 15 support @damingerdai
> 
> @yociduo
> 
> ```
> No .circleci/config.yml was found in your project. Add a configuration file to your repository or refer to [documentation](https://circleci.com/docs/2.0/configuration-reference/).
> ```
> 
> please remove Circle CI

@yociduo @damingerdai 

And please change the peerDependencies, see #67
