### ISSUE TITLE
Can't import the named export X from non EcmaScript module

### ISSUE THREAD

**Issue by farshid1** [yociduo/ngx-pendo#63]
I'm having trouble building my application which is on top of nx. I keep getting the `Can't import the named export X from non EcmaScript module` error. This is due to this library building to mjs files. Are there any resolutions/suggestions for this issue? thanks

**Comment by damingerdai** [comment]
cloud you share code with github or other?

**Comment by farshid1** [comment]
@damingerdai Thanks for the quick response! It's hard to share code as this is a large project but I simply followed the installation instructions and imported `NgxPendoModule` and `NgxPendoService` from the library. I think I have a pretty good idea what the issue is which is related to my build system. I basically need to configure the build system to allow mjs exports. [This](https://nx.dev/recipes/other/customize-webpack) for example is a webpack solution.

I was just wondering if you have some ideas right off the bat.
