### ISSUE TITLE
Use version ranges for angular peerDependencies

### ISSUE THREAD

**Issue by PooSham** [yociduo/ngx-pendo#67]
It seems like there hasn't been a new release of this package after the update to angular 15, which breaks projects using this package. The reason for this seems to be that the CircleCI pipeline failed for some reason. 

I understand that you don't have time to update the project the same minute as new versions of Angular are released, but I would recommend that you use ranges in the peerDependencies that allow people to update to new versions when they like. [Because Angular always leave a feature for 2 more versions after they've deprecated it](https://angular.io/guide/releases#deprecation-practices), you don't need to worry that ngx-pendo will be broken in later releases. 

I would suggest that you set the peerDependencies versions to `">= 15.0.0 < 18.0.0"` now, and some time after Angular 16 is released,  you change it to `">= 16.0.0 < 19.0.0"` etc. Every time you do an update, you check if there are any deprecation warnings. You fix those warnings whenever you have time to, without any stress, knowing that it will still work for more than one year.

**Comment by yociduo** [comment]
Updated https://github.com/yociduo/ngx-pendo/commit/0e09887a5de6c07615a247d8055399dc4296811f. 
I will release this in next version. Thanks
