### ISSUE TITLE
Pendo api key / section issue

### ISSUE THREAD

**Issue by BruneXX** [yociduo/ngx-pendo#84]
Error: node_modules/ngx-pendo/lib/ngx-pendo-id.directive.d.ts:18:90 - error TS2344: Type '{ pendoId: { alias: "ngx-pendo-id"; required: false; }; inherit: { alias: "ngx-pendo-inherit"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"pendoId"' is incompatible with index signature.
    Type '{ alias: "ngx-pendo-id"; required: false; }' is not assignable to type 'string'.

18     static ɵdir: i0.ɵɵDirectiveDeclaration<NgxPendoIdDirective, "[ngx-pendo-id]", never, { "pendoId": { "alias": "ngx-pendo-id"; "required": false; }; "inherit": { "alias": "ngx-pendo-inherit"; "required": false; }; }, {}, never, never, false, never>;

Error: node_modules/ngx-pendo/lib/ngx-pendo-section.directive.d.ts:18:100 - error TS2344: Type '{ pendoSection: { alias: "ngx-pendo-section"; required: false; }; inherit: { alias: "ngx-pendo-inherit"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"pendoSection"' is incompatible with index signature.
    Type '{ alias: "ngx-pendo-section"; required: false; }' is not assignable to type 'string'.

18     static ɵdir: i0.ɵɵDirectiveDeclaration<NgxPendoSectionDirective, "[ngx-pendo-section]", never, { "pendoSection": { "alias": "ngx-pendo-section"; "required": false; }; "inherit": { "alias": "ngx-pendo-inherit"; "required": false; }; }, {}, ["idDirectives", "sectionDirectives", "allIdDirectives"], never, false, never>;

**Comment by damingerdai** [comment]
what is your angular version

**Comment by BruneXX** [comment]
Hi @damingerdai it's **15.2.9**

**Comment by BruneXX** [comment]
Hi @damingerdai Do you have any update on this? thanks!

**Comment by damingerdai** [comment]
Can you provide a minimal  demo?

**Comment by damingerdai** [comment]
i test on my local pc with angular 15.2.9 and ngx-pendo 1.11.0. it look like work for me

**Comment by BruneXX** [comment]
Hi @damingerdai I think then the issue is that I'm using the ngx-pendo **v1.12.0**
I'm reviewing that right now, but if that's the case can you please add a table with to match/map the Angular version and ngx-pendo version to use? Thanks!

**Comment by BruneXX** [comment]
@damingerdai confirmed, in angular **v15.2.9** with ngx-pendo > **v1.11.0** works fine, I think ngx-pendo **v1.12.0** will be just for newer versions. it will be awesome if we could have a mapping table. Thanks!
