### ISSUE TITLE
Id naming convention configurable

### ISSUE THREAD

**Issue by mcrightworks** [yociduo/ngx-pendo#92]
Thanks for creating this wrapper!
Would it be possible to make the naming convention of the id configurable?
```
<div ngx-pendo-section="section">
  <button ngx-pendo-id="click_test">Click Test</button>
</div>
```
`ngx-pendo-section => my-custom-section`
`ngx-pendo-id => my-custom-id`

**Comment by yociduo** [comment]
@mcrightworks suggest fork one and replace the selector name for this two directives.
