### ISSUE TITLE
Problem with NgxPendoSectionDirective

### ISSUE THREAD

**Issue by piter292922** [yociduo/ngx-pendo#94]
Error: node_modules/ngx-pendo/lib/ngx-pendo-id.directive.d.ts:18:90 - error TS2344: Type '{ pendoId: { alias: "ngx-pendo-id"; required: false; }; inherit: { alias: "ngx-pendo-inherit"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.

Property '"pendoId"' is incompatible with index signature.
Type '{ alias: "ngx-pendo-id"; required: false; }' is not assignable to type 'string'.

static ɵdir: i0.ɵɵDirectiveDeclaration<NgxPendoIdDirective, "[ngx-pendo-id]", never, { "pendoId": { "alias": "ngx-pendo-id"; "required": false; }; "inherit": { "alias": "ngx-pendo-inherit"; "required": false; }; }, {}, never, never, false, never>;

**Comment by yociduo** [comment]
Could your provide the package version and angular version?

**Comment by piter292922** [comment]
Yes, ngx-pendo 1.14.1 (newest i think) and Angular 15.2.9

**Comment by damingerdai** [comment]
Cloud you provide your code?

**Comment by yociduo** [comment]
@piter292922 I created a [demo](https://stackblitz.com/edit/angular-wvce1m) in the online editor, you can take a look at how to reproduce the issue.

**Comment by yociduo** [comment]
@piter292922 I have reproduced this issue please use ngx-pendo@1.11.0, I will update the compatibility to the document.

**Comment by piter292922** [comment]
Thanks a lot!
